window.liveUpdateTime = '2026/06/11 08:49';
window.liveVacationData = [
  {
    "city": "基隆市",
    "district": "萬里區",
    "historyCount": 32,
    "status": "無",
    "note": "-",
    "daysPassed": "229天",
    "lastDate": "2025/10/25",
    "isFirstOfCity": true,
    "cityRowspan": 10
  },
  {
    "city": "基隆市",
    "district": "金山區",
    "historyCount": 34,
    "status": "無",
    "note": "-",
    "daysPassed": "252天",
    "lastDate": "2025/10/02",
    "isFirstOfCity": false,
    "cityRowspan": 10
  },
  {
    "city": "基隆市",
    "district": "板橋區",
    "historyCount": 34,
    "status": "無",
    "note": "-",
    "daysPassed": "150天",
    "lastDate": "2026/01/12",
    "isFirstOfCity": false,
    "cityRowspan": 10
  },
  {
    "city": "基隆市",
    "district": "七堵區",
    "historyCount": 36,
    "status": "無",
    "note": "-",
    "daysPassed": "136天",
    "lastDate": "2026/01/26",
    "isFirstOfCity": false,
    "cityRowspan": 10
  },
  {
    "city": "基隆市",
    "district": "安樂區",
    "historyCount": 33,
    "status": "無",
    "note": "-",
    "daysPassed": "165天",
    "lastDate": "2025/12/28",
    "isFirstOfCity": false,
    "cityRowspan": 10
  },
  {
    "city": "基隆市",
    "district": "仁愛區",
    "historyCount": 32,
    "status": "無",
    "note": "-",
    "daysPassed": "173天",
    "lastDate": "2025/12/20",
    "isFirstOfCity": false,
    "cityRowspan": 10
  },
  {
    "city": "基隆市",
    "district": "信義區",
    "historyCount": 29,
    "status": "無",
    "note": "-",
    "daysPassed": "157天",
    "lastDate": "2026/01/05",
    "isFirstOfCity": false,
    "cityRowspan": 10
  },
  {
    "city": "基隆市",
    "district": "中正區",
    "historyCount": 33,
    "status": "無",
    "note": "-",
    "daysPassed": "203天",
    "lastDate": "2025/11/20",
    "isFirstOfCity": false,
    "cityRowspan": 10
  },
  {
    "city": "基隆市",
    "district": "中山區",
    "historyCount": 36,
    "status": "無",
    "note": "-",
    "daysPassed": "198天",
    "lastDate": "2025/11/25",
    "isFirstOfCity": false,
    "cityRowspan": 10
  },
  {
    "city": "基隆市",
    "district": "暖暖區",
    "historyCount": 34,
    "status": "無",
    "note": "-",
    "daysPassed": "190天",
    "lastDate": "2025/12/03",
    "isFirstOfCity": false,
    "cityRowspan": 10
  },
  {
    "city": "台北市",
    "district": "北投區",
    "historyCount": 32,
    "status": "無",
    "note": "-",
    "daysPassed": "251天",
    "lastDate": "2025/10/03",
    "isFirstOfCity": true,
    "cityRowspan": 12
  },
  {
    "city": "台北市",
    "district": "士林區",
    "historyCount": 31,
    "status": "無",
    "note": "-",
    "daysPassed": "266天",
    "lastDate": "2025/09/18",
    "isFirstOfCity": false,
    "cityRowspan": 12
  },
  {
    "city": "台北市",
    "district": "內湖區",
    "historyCount": 32,
    "status": "無",
    "note": "-",
    "daysPassed": "182天",
    "lastDate": "2025/12/11",
    "isFirstOfCity": false,
    "cityRowspan": 12
  },
  {
    "city": "台北市",
    "district": "中山區",
    "historyCount": 32,
    "status": "無",
    "note": "-",
    "daysPassed": "210天",
    "lastDate": "2025/11/13",
    "isFirstOfCity": false,
    "cityRowspan": 12
  },
  {
    "city": "台北市",
    "district": "大同區",
    "historyCount": 30,
    "status": "無",
    "note": "-",
    "daysPassed": "212天",
    "lastDate": "2025/11/11",
    "isFirstOfCity": false,
    "cityRowspan": 12
  },
  {
    "city": "台北市",
    "district": "松山區",
    "historyCount": 29,
    "status": "無",
    "note": "-",
    "daysPassed": "174天",
    "lastDate": "2025/12/19",
    "isFirstOfCity": false,
    "cityRowspan": 12
  },
  {
    "city": "台北市",
    "district": "萬華區",
    "historyCount": 33,
    "status": "無",
    "note": "-",
    "daysPassed": "158天",
    "lastDate": "2026/01/04",
    "isFirstOfCity": false,
    "cityRowspan": 12
  },
  {
    "city": "台北市",
    "district": "中正區",
    "historyCount": 29,
    "status": "無",
    "note": "-",
    "daysPassed": "187天",
    "lastDate": "2025/12/06",
    "isFirstOfCity": false,
    "cityRowspan": 12
  },
  {
    "city": "台北市",
    "district": "大安區",
    "historyCount": 29,
    "status": "無",
    "note": "-",
    "daysPassed": "193天",
    "lastDate": "2025/11/30",
    "isFirstOfCity": false,
    "cityRowspan": 12
  },
  {
    "city": "台北市",
    "district": "信義區",
    "historyCount": 32,
    "status": "無",
    "note": "-",
    "daysPassed": "189天",
    "lastDate": "2025/12/04",
    "isFirstOfCity": false,
    "cityRowspan": 12
  },
  {
    "city": "台北市",
    "district": "南港區",
    "historyCount": 35,
    "status": "無",
    "note": "-",
    "daysPassed": "241天",
    "lastDate": "2025/10/13",
    "isFirstOfCity": false,
    "cityRowspan": 12
  },
  {
    "city": "台北市",
    "district": "文山區",
    "historyCount": 30,
    "status": "無",
    "note": "-",
    "daysPassed": "186天",
    "lastDate": "2025/12/07",
    "isFirstOfCity": false,
    "cityRowspan": 12
  },
  {
    "city": "新北市",
    "district": "石門區",
    "historyCount": 29,
    "status": "無",
    "note": "-",
    "daysPassed": "137天",
    "lastDate": "2026/01/25",
    "isFirstOfCity": true,
    "cityRowspan": 27
  },
  {
    "city": "新北市",
    "district": "三芝區",
    "historyCount": 30,
    "status": "無",
    "note": "-",
    "daysPassed": "154天",
    "lastDate": "2026/01/08",
    "isFirstOfCity": false,
    "cityRowspan": 27
  },
  {
    "city": "新北市",
    "district": "淡水區",
    "historyCount": 28,
    "status": "無",
    "note": "-",
    "daysPassed": "140天",
    "lastDate": "2026/01/22",
    "isFirstOfCity": false,
    "cityRowspan": 27
  },
  {
    "city": "新北市",
    "district": "八里區",
    "historyCount": 35,
    "status": "無",
    "note": "-",
    "daysPassed": "227天",
    "lastDate": "2025/10/27",
    "isFirstOfCity": false,
    "cityRowspan": 27
  },
  {
    "city": "新北市",
    "district": "林口區",
    "historyCount": 35,
    "status": "無",
    "note": "-",
    "daysPassed": "173天",
    "lastDate": "2025/12/20",
    "isFirstOfCity": false,
    "cityRowspan": 27
  },
  {
    "city": "新北市",
    "district": "五股區",
    "historyCount": 32,
    "status": "無",
    "note": "-",
    "daysPassed": "151天",
    "lastDate": "2026/01/11",
    "isFirstOfCity": false,
    "cityRowspan": 27
  },
  {
    "city": "新北市",
    "district": "蘆洲區",
    "historyCount": 32,
    "status": "無",
    "note": "-",
    "daysPassed": "209天",
    "lastDate": "2025/11/14",
    "isFirstOfCity": false,
    "cityRowspan": 27
  },
  {
    "city": "新北市",
    "district": "三重區",
    "historyCount": 30,
    "status": "無",
    "note": "-",
    "daysPassed": "236天",
    "lastDate": "2025/10/18",
    "isFirstOfCity": false,
    "cityRowspan": 27
  },
  {
    "city": "新北市",
    "district": "新莊區",
    "historyCount": 30,
    "status": "無",
    "note": "-",
    "daysPassed": "143天",
    "lastDate": "2026/01/19",
    "isFirstOfCity": false,
    "cityRowspan": 27
  },
  {
    "city": "新北市",
    "district": "泰山區",
    "historyCount": 35,
    "status": "無",
    "note": "-",
    "daysPassed": "280天",
    "lastDate": "2025/09/04",
    "isFirstOfCity": false,
    "cityRowspan": 27
  },
  {
    "city": "新北市",
    "district": "板橋區",
    "historyCount": 31,
    "status": "無",
    "note": "-",
    "daysPassed": "122天",
    "lastDate": "2026/02/09",
    "isFirstOfCity": false,
    "cityRowspan": 27
  },
  {
    "city": "新北市",
    "district": "中和區",
    "historyCount": 34,
    "status": "無",
    "note": "-",
    "daysPassed": "234天",
    "lastDate": "2025/10/20",
    "isFirstOfCity": false,
    "cityRowspan": 27
  },
  {
    "city": "新北市",
    "district": "永和區",
    "historyCount": 29,
    "status": "無",
    "note": "-",
    "daysPassed": "228天",
    "lastDate": "2025/10/26",
    "isFirstOfCity": false,
    "cityRowspan": 27
  },
  {
    "city": "新北市",
    "district": "土城區",
    "historyCount": 30,
    "status": "無",
    "note": "-",
    "daysPassed": "133天",
    "lastDate": "2026/01/29",
    "isFirstOfCity": false,
    "cityRowspan": 27
  },
  {
    "city": "新北市",
    "district": "樹林區",
    "historyCount": 31,
    "status": "無",
    "note": "-",
    "daysPassed": "253天",
    "lastDate": "2025/10/01",
    "isFirstOfCity": false,
    "cityRowspan": 27
  },
  {
    "city": "新北市",
    "district": "鶯歌區",
    "historyCount": 35,
    "status": "無",
    "note": "-",
    "daysPassed": "229天",
    "lastDate": "2025/10/25",
    "isFirstOfCity": false,
    "cityRowspan": 27
  },
  {
    "city": "新北市",
    "district": "三峽區",
    "historyCount": 30,
    "status": "無",
    "note": "-",
    "daysPassed": "138天",
    "lastDate": "2026/01/24",
    "isFirstOfCity": false,
    "cityRowspan": 27
  },
  {
    "city": "新北市",
    "district": "新店區",
    "historyCount": 28,
    "status": "無",
    "note": "-",
    "daysPassed": "192天",
    "lastDate": "2025/12/01",
    "isFirstOfCity": false,
    "cityRowspan": 27
  },
  {
    "city": "新北市",
    "district": "汐止區",
    "historyCount": 31,
    "status": "無",
    "note": "-",
    "daysPassed": "258天",
    "lastDate": "2025/09/26",
    "isFirstOfCity": false,
    "cityRowspan": 27
  },
  {
    "city": "新北市",
    "district": "深坑區",
    "historyCount": 34,
    "status": "無",
    "note": "-",
    "daysPassed": "145天",
    "lastDate": "2026/01/17",
    "isFirstOfCity": false,
    "cityRowspan": 27
  },
  {
    "city": "新北市",
    "district": "石碇區",
    "historyCount": 30,
    "status": "無",
    "note": "-",
    "daysPassed": "201天",
    "lastDate": "2025/11/22",
    "isFirstOfCity": false,
    "cityRowspan": 27
  },
  {
    "city": "新北市",
    "district": "坪林區",
    "historyCount": 35,
    "status": "無",
    "note": "-",
    "daysPassed": "198天",
    "lastDate": "2025/11/25",
    "isFirstOfCity": false,
    "cityRowspan": 27
  },
  {
    "city": "新北市",
    "district": "烏來區",
    "historyCount": 29,
    "status": "無",
    "note": "-",
    "daysPassed": "208天",
    "lastDate": "2025/11/15",
    "isFirstOfCity": false,
    "cityRowspan": 27
  },
  {
    "city": "新北市",
    "district": "瑞芳區",
    "historyCount": 28,
    "status": "無",
    "note": "-",
    "daysPassed": "188天",
    "lastDate": "2025/12/05",
    "isFirstOfCity": false,
    "cityRowspan": 27
  },
  {
    "city": "新北市",
    "district": "雙溪區",
    "historyCount": 34,
    "status": "無",
    "note": "-",
    "daysPassed": "148天",
    "lastDate": "2026/01/14",
    "isFirstOfCity": false,
    "cityRowspan": 27
  },
  {
    "city": "新北市",
    "district": "貢寮區",
    "historyCount": 29,
    "status": "無",
    "note": "-",
    "daysPassed": "181天",
    "lastDate": "2025/12/12",
    "isFirstOfCity": false,
    "cityRowspan": 27
  },
  {
    "city": "新北市",
    "district": "平溪區",
    "historyCount": 29,
    "status": "無",
    "note": "-",
    "daysPassed": "166天",
    "lastDate": "2025/12/27",
    "isFirstOfCity": false,
    "cityRowspan": 27
  },
  {
    "city": "桃園市",
    "district": "蘆竹區",
    "historyCount": 33,
    "status": "無",
    "note": "-",
    "daysPassed": "215天",
    "lastDate": "2025/11/08",
    "isFirstOfCity": true,
    "cityRowspan": 13
  },
  {
    "city": "桃園市",
    "district": "大園區",
    "historyCount": 36,
    "status": "無",
    "note": "-",
    "daysPassed": "240天",
    "lastDate": "2025/10/14",
    "isFirstOfCity": false,
    "cityRowspan": 13
  },
  {
    "city": "桃園市",
    "district": "觀音區",
    "historyCount": 31,
    "status": "無",
    "note": "-",
    "daysPassed": "154天",
    "lastDate": "2026/01/08",
    "isFirstOfCity": false,
    "cityRowspan": 13
  },
  {
    "city": "桃園市",
    "district": "新屋區",
    "historyCount": 31,
    "status": "無",
    "note": "-",
    "daysPassed": "129天",
    "lastDate": "2026/02/02",
    "isFirstOfCity": false,
    "cityRowspan": 13
  },
  {
    "city": "桃園市",
    "district": "龜山區",
    "historyCount": 30,
    "status": "無",
    "note": "-",
    "daysPassed": "272天",
    "lastDate": "2025/09/12",
    "isFirstOfCity": false,
    "cityRowspan": 13
  },
  {
    "city": "桃園市",
    "district": "桃園區",
    "historyCount": 31,
    "status": "無",
    "note": "-",
    "daysPassed": "148天",
    "lastDate": "2026/01/14",
    "isFirstOfCity": false,
    "cityRowspan": 13
  },
  {
    "city": "桃園市",
    "district": "八德區",
    "historyCount": 35,
    "status": "無",
    "note": "-",
    "daysPassed": "210天",
    "lastDate": "2025/11/13",
    "isFirstOfCity": false,
    "cityRowspan": 13
  },
  {
    "city": "桃園市",
    "district": "中壢區",
    "historyCount": 31,
    "status": "無",
    "note": "-",
    "daysPassed": "221天",
    "lastDate": "2025/11/02",
    "isFirstOfCity": false,
    "cityRowspan": 13
  },
  {
    "city": "桃園市",
    "district": "平鎮區",
    "historyCount": 30,
    "status": "無",
    "note": "-",
    "daysPassed": "263天",
    "lastDate": "2025/09/21",
    "isFirstOfCity": false,
    "cityRowspan": 13
  },
  {
    "city": "桃園市",
    "district": "楊梅區",
    "historyCount": 28,
    "status": "無",
    "note": "-",
    "daysPassed": "129天",
    "lastDate": "2026/02/02",
    "isFirstOfCity": false,
    "cityRowspan": 13
  },
  {
    "city": "桃園市",
    "district": "大溪區",
    "historyCount": 28,
    "status": "無",
    "note": "-",
    "daysPassed": "277天",
    "lastDate": "2025/09/07",
    "isFirstOfCity": false,
    "cityRowspan": 13
  },
  {
    "city": "桃園市",
    "district": "龍潭區",
    "historyCount": 31,
    "status": "無",
    "note": "-",
    "daysPassed": "191天",
    "lastDate": "2025/12/02",
    "isFirstOfCity": false,
    "cityRowspan": 13
  },
  {
    "city": "桃園市",
    "district": "復興區",
    "historyCount": 31,
    "status": "無",
    "note": "-",
    "daysPassed": "263天",
    "lastDate": "2025/09/21",
    "isFirstOfCity": false,
    "cityRowspan": 13
  },
  {
    "city": "新竹市",
    "district": "北區",
    "historyCount": 34,
    "status": "無",
    "note": "-",
    "daysPassed": "249天",
    "lastDate": "2025/10/05",
    "isFirstOfCity": true,
    "cityRowspan": 3
  },
  {
    "city": "新竹市",
    "district": "東區",
    "historyCount": 32,
    "status": "無",
    "note": "-",
    "daysPassed": "222天",
    "lastDate": "2025/11/01",
    "isFirstOfCity": false,
    "cityRowspan": 3
  },
  {
    "city": "新竹市",
    "district": "香山區",
    "historyCount": 33,
    "status": "無",
    "note": "-",
    "daysPassed": "132天",
    "lastDate": "2026/01/30",
    "isFirstOfCity": false,
    "cityRowspan": 3
  },
  {
    "city": "新竹縣",
    "district": "新豐鄉",
    "historyCount": 36,
    "status": "無",
    "note": "-",
    "daysPassed": "224天",
    "lastDate": "2025/10/30",
    "isFirstOfCity": true,
    "cityRowspan": 13
  },
  {
    "city": "新竹縣",
    "district": "湖口鄉",
    "historyCount": 34,
    "status": "無",
    "note": "-",
    "daysPassed": "253天",
    "lastDate": "2025/10/01",
    "isFirstOfCity": false,
    "cityRowspan": 13
  },
  {
    "city": "新竹縣",
    "district": "竹北市",
    "historyCount": 32,
    "status": "無",
    "note": "-",
    "daysPassed": "226天",
    "lastDate": "2025/10/28",
    "isFirstOfCity": false,
    "cityRowspan": 13
  },
  {
    "city": "新竹縣",
    "district": "新埔鎮",
    "historyCount": 30,
    "status": "無",
    "note": "-",
    "daysPassed": "200天",
    "lastDate": "2025/11/23",
    "isFirstOfCity": false,
    "cityRowspan": 13
  },
  {
    "city": "新竹縣",
    "district": "關西鎮",
    "historyCount": 36,
    "status": "無",
    "note": "-",
    "daysPassed": "165天",
    "lastDate": "2025/12/28",
    "isFirstOfCity": false,
    "cityRowspan": 13
  },
  {
    "city": "新竹縣",
    "district": "芎林鄉",
    "historyCount": 28,
    "status": "無",
    "note": "-",
    "daysPassed": "219天",
    "lastDate": "2025/11/04",
    "isFirstOfCity": false,
    "cityRowspan": 13
  },
  {
    "city": "新竹縣",
    "district": "竹東鎮",
    "historyCount": 28,
    "status": "無",
    "note": "-",
    "daysPassed": "267天",
    "lastDate": "2025/09/17",
    "isFirstOfCity": false,
    "cityRowspan": 13
  },
  {
    "city": "新竹縣",
    "district": "寶山鄉",
    "historyCount": 30,
    "status": "無",
    "note": "-",
    "daysPassed": "245天",
    "lastDate": "2025/10/09",
    "isFirstOfCity": false,
    "cityRowspan": 13
  },
  {
    "city": "新竹縣",
    "district": "橫山鄉",
    "historyCount": 32,
    "status": "無",
    "note": "-",
    "daysPassed": "184天",
    "lastDate": "2025/12/09",
    "isFirstOfCity": false,
    "cityRowspan": 13
  },
  {
    "city": "新竹縣",
    "district": "北埔鄉",
    "historyCount": 34,
    "status": "無",
    "note": "-",
    "daysPassed": "180天",
    "lastDate": "2025/12/13",
    "isFirstOfCity": false,
    "cityRowspan": 13
  },
  {
    "city": "新竹縣",
    "district": "峨眉鄉",
    "historyCount": 35,
    "status": "無",
    "note": "-",
    "daysPassed": "227天",
    "lastDate": "2025/10/27",
    "isFirstOfCity": false,
    "cityRowspan": 13
  },
  {
    "city": "新竹縣",
    "district": "尖石鄉",
    "historyCount": 36,
    "status": "無",
    "note": "-",
    "daysPassed": "125天",
    "lastDate": "2026/02/06",
    "isFirstOfCity": false,
    "cityRowspan": 13
  },
  {
    "city": "新竹縣",
    "district": "五峰鄉",
    "historyCount": 33,
    "status": "無",
    "note": "-",
    "daysPassed": "225天",
    "lastDate": "2025/10/29",
    "isFirstOfCity": false,
    "cityRowspan": 13
  },
  {
    "city": "苗栗縣",
    "district": "竹南鎮",
    "historyCount": 34,
    "status": "無",
    "note": "-",
    "daysPassed": "185天",
    "lastDate": "2025/12/08",
    "isFirstOfCity": true,
    "cityRowspan": 16
  },
  {
    "city": "苗栗縣",
    "district": "頭份市",
    "historyCount": 32,
    "status": "無",
    "note": "-",
    "daysPassed": "140天",
    "lastDate": "2026/01/22",
    "isFirstOfCity": false,
    "cityRowspan": 16
  },
  {
    "city": "苗栗縣",
    "district": "造橋鄉",
    "historyCount": 28,
    "status": "無",
    "note": "-",
    "daysPassed": "196天",
    "lastDate": "2025/11/27",
    "isFirstOfCity": false,
    "cityRowspan": 16
  },
  {
    "city": "苗栗縣",
    "district": "後龍鎮",
    "historyCount": 35,
    "status": "無",
    "note": "-",
    "daysPassed": "218天",
    "lastDate": "2025/11/05",
    "isFirstOfCity": false,
    "cityRowspan": 16
  },
  {
    "city": "苗栗縣",
    "district": "西湖鄉",
    "historyCount": 33,
    "status": "無",
    "note": "-",
    "daysPassed": "221天",
    "lastDate": "2025/11/02",
    "isFirstOfCity": false,
    "cityRowspan": 16
  },
  {
    "city": "苗栗縣",
    "district": "頭屋鄉",
    "historyCount": 32,
    "status": "無",
    "note": "-",
    "daysPassed": "169天",
    "lastDate": "2025/12/24",
    "isFirstOfCity": false,
    "cityRowspan": 16
  },
  {
    "city": "苗栗縣",
    "district": "苗栗市",
    "historyCount": 31,
    "status": "無",
    "note": "-",
    "daysPassed": "203天",
    "lastDate": "2025/11/20",
    "isFirstOfCity": false,
    "cityRowspan": 16
  },
  {
    "city": "苗栗縣",
    "district": "公館鄉",
    "historyCount": 31,
    "status": "無",
    "note": "-",
    "daysPassed": "131天",
    "lastDate": "2026/01/31",
    "isFirstOfCity": false,
    "cityRowspan": 16
  },
  {
    "city": "苗栗縣",
    "district": "銅鑼鄉",
    "historyCount": 36,
    "status": "無",
    "note": "-",
    "daysPassed": "141天",
    "lastDate": "2026/01/21",
    "isFirstOfCity": false,
    "cityRowspan": 16
  },
  {
    "city": "苗栗縣",
    "district": "通霄鎮",
    "historyCount": 31,
    "status": "無",
    "note": "-",
    "daysPassed": "139天",
    "lastDate": "2026/01/23",
    "isFirstOfCity": false,
    "cityRowspan": 16
  },
  {
    "city": "苗栗縣",
    "district": "苑裡鎮",
    "historyCount": 35,
    "status": "無",
    "note": "-",
    "daysPassed": "184天",
    "lastDate": "2025/12/09",
    "isFirstOfCity": false,
    "cityRowspan": 16
  },
  {
    "city": "苗栗縣",
    "district": "三義鄉",
    "historyCount": 33,
    "status": "無",
    "note": "-",
    "daysPassed": "139天",
    "lastDate": "2026/01/23",
    "isFirstOfCity": false,
    "cityRowspan": 16
  },
  {
    "city": "苗栗縣",
    "district": "大湖鄉",
    "historyCount": 31,
    "status": "無",
    "note": "-",
    "daysPassed": "201天",
    "lastDate": "2025/11/22",
    "isFirstOfCity": false,
    "cityRowspan": 16
  },
  {
    "city": "苗栗縣",
    "district": "獅潭鄉",
    "historyCount": 30,
    "status": "無",
    "note": "-",
    "daysPassed": "176天",
    "lastDate": "2025/12/17",
    "isFirstOfCity": false,
    "cityRowspan": 16
  },
  {
    "city": "苗栗縣",
    "district": "卓蘭鎮",
    "historyCount": 30,
    "status": "無",
    "note": "-",
    "daysPassed": "121天",
    "lastDate": "2026/02/10",
    "isFirstOfCity": false,
    "cityRowspan": 16
  },
  {
    "city": "苗栗縣",
    "district": "泰安鄉",
    "historyCount": 30,
    "status": "無",
    "note": "-",
    "daysPassed": "208天",
    "lastDate": "2025/11/15",
    "isFirstOfCity": false,
    "cityRowspan": 16
  },
  {
    "city": "台中市",
    "district": "大甲區",
    "historyCount": 34,
    "status": "無",
    "note": "-",
    "daysPassed": "214天",
    "lastDate": "2025/11/09",
    "isFirstOfCity": true,
    "cityRowspan": 27
  },
  {
    "city": "台中市",
    "district": "大安區",
    "historyCount": 28,
    "status": "無",
    "note": "-",
    "daysPassed": "272天",
    "lastDate": "2025/09/12",
    "isFirstOfCity": false,
    "cityRowspan": 27
  },
  {
    "city": "台中市",
    "district": "外埔區",
    "historyCount": 31,
    "status": "無",
    "note": "-",
    "daysPassed": "187天",
    "lastDate": "2025/12/06",
    "isFirstOfCity": false,
    "cityRowspan": 27
  },
  {
    "city": "台中市",
    "district": "后里區",
    "historyCount": 31,
    "status": "無",
    "note": "-",
    "daysPassed": "193天",
    "lastDate": "2025/11/30",
    "isFirstOfCity": false,
    "cityRowspan": 27
  },
  {
    "city": "台中市",
    "district": "清水區",
    "historyCount": 30,
    "status": "無",
    "note": "-",
    "daysPassed": "231天",
    "lastDate": "2025/10/23",
    "isFirstOfCity": false,
    "cityRowspan": 27
  },
  {
    "city": "台中市",
    "district": "神岡區",
    "historyCount": 30,
    "status": "無",
    "note": "-",
    "daysPassed": "169天",
    "lastDate": "2025/12/24",
    "isFirstOfCity": false,
    "cityRowspan": 27
  },
  {
    "city": "台中市",
    "district": "豐原區",
    "historyCount": 34,
    "status": "無",
    "note": "-",
    "daysPassed": "216天",
    "lastDate": "2025/11/07",
    "isFirstOfCity": false,
    "cityRowspan": 27
  },
  {
    "city": "台中市",
    "district": "石岡區",
    "historyCount": 32,
    "status": "無",
    "note": "-",
    "daysPassed": "187天",
    "lastDate": "2025/12/06",
    "isFirstOfCity": false,
    "cityRowspan": 27
  },
  {
    "city": "台中市",
    "district": "東勢區",
    "historyCount": 32,
    "status": "無",
    "note": "-",
    "daysPassed": "128天",
    "lastDate": "2026/02/03",
    "isFirstOfCity": false,
    "cityRowspan": 27
  },
  {
    "city": "台中市",
    "district": "新社區",
    "historyCount": 29,
    "status": "無",
    "note": "-",
    "daysPassed": "182天",
    "lastDate": "2025/12/11",
    "isFirstOfCity": false,
    "cityRowspan": 27
  },
  {
    "city": "台中市",
    "district": "沙鹿區",
    "historyCount": 35,
    "status": "無",
    "note": "-",
    "daysPassed": "140天",
    "lastDate": "2026/01/22",
    "isFirstOfCity": false,
    "cityRowspan": 27
  },
  {
    "city": "台中市",
    "district": "梧棲區",
    "historyCount": 30,
    "status": "無",
    "note": "-",
    "daysPassed": "259天",
    "lastDate": "2025/09/25",
    "isFirstOfCity": false,
    "cityRowspan": 27
  },
  {
    "city": "台中市",
    "district": "龍井區",
    "historyCount": 35,
    "status": "無",
    "note": "-",
    "daysPassed": "120天",
    "lastDate": "2026/02/11",
    "isFirstOfCity": false,
    "cityRowspan": 27
  },
  {
    "city": "台中市",
    "district": "大肚區",
    "historyCount": 28,
    "status": "無",
    "note": "-",
    "daysPassed": "158天",
    "lastDate": "2026/01/04",
    "isFirstOfCity": false,
    "cityRowspan": 27
  },
  {
    "city": "台中市",
    "district": "烏日區",
    "historyCount": 34,
    "status": "無",
    "note": "-",
    "daysPassed": "239天",
    "lastDate": "2025/10/15",
    "isFirstOfCity": false,
    "cityRowspan": 27
  },
  {
    "city": "台中市",
    "district": "西屯區",
    "historyCount": 29,
    "status": "無",
    "note": "-",
    "daysPassed": "134天",
    "lastDate": "2026/01/28",
    "isFirstOfCity": false,
    "cityRowspan": 27
  },
  {
    "city": "台中市",
    "district": "北屯區",
    "historyCount": 28,
    "status": "無",
    "note": "-",
    "daysPassed": "128天",
    "lastDate": "2026/02/03",
    "isFirstOfCity": false,
    "cityRowspan": 27
  },
  {
    "city": "台中市",
    "district": "北區",
    "historyCount": 36,
    "status": "無",
    "note": "-",
    "daysPassed": "231天",
    "lastDate": "2025/10/23",
    "isFirstOfCity": false,
    "cityRowspan": 27
  },
  {
    "city": "台中市",
    "district": "中區",
    "historyCount": 32,
    "status": "無",
    "note": "-",
    "daysPassed": "262天",
    "lastDate": "2025/09/22",
    "isFirstOfCity": false,
    "cityRowspan": 27
  },
  {
    "city": "台中市",
    "district": "東區",
    "historyCount": 29,
    "status": "無",
    "note": "-",
    "daysPassed": "175天",
    "lastDate": "2025/12/18",
    "isFirstOfCity": false,
    "cityRowspan": 27
  },
  {
    "city": "台中市",
    "district": "南區",
    "historyCount": 29,
    "status": "無",
    "note": "-",
    "daysPassed": "249天",
    "lastDate": "2025/10/05",
    "isFirstOfCity": false,
    "cityRowspan": 27
  },
  {
    "city": "台中市",
    "district": "西區",
    "historyCount": 34,
    "status": "無",
    "note": "-",
    "daysPassed": "225天",
    "lastDate": "2025/10/29",
    "isFirstOfCity": false,
    "cityRowspan": 27
  },
  {
    "city": "台中市",
    "district": "南屯區",
    "historyCount": 31,
    "status": "無",
    "note": "-",
    "daysPassed": "246天",
    "lastDate": "2025/10/08",
    "isFirstOfCity": false,
    "cityRowspan": 27
  },
  {
    "city": "台中市",
    "district": "太平區",
    "historyCount": 30,
    "status": "無",
    "note": "-",
    "daysPassed": "165天",
    "lastDate": "2025/12/28",
    "isFirstOfCity": false,
    "cityRowspan": 27
  },
  {
    "city": "台中市",
    "district": "大里區",
    "historyCount": 36,
    "status": "無",
    "note": "-",
    "daysPassed": "250天",
    "lastDate": "2025/10/04",
    "isFirstOfCity": false,
    "cityRowspan": 27
  },
  {
    "city": "台中市",
    "district": "霧峰區",
    "historyCount": 34,
    "status": "無",
    "note": "-",
    "daysPassed": "245天",
    "lastDate": "2025/10/09",
    "isFirstOfCity": false,
    "cityRowspan": 27
  },
  {
    "city": "台中市",
    "district": "和平區",
    "historyCount": 28,
    "status": "無",
    "note": "-",
    "daysPassed": "280天",
    "lastDate": "2025/09/04",
    "isFirstOfCity": false,
    "cityRowspan": 27
  },
  {
    "city": "彰化縣",
    "district": "伸港鄉",
    "historyCount": 30,
    "status": "無",
    "note": "-",
    "daysPassed": "129天",
    "lastDate": "2026/02/02",
    "isFirstOfCity": true,
    "cityRowspan": 26
  },
  {
    "city": "彰化縣",
    "district": "線西鄉",
    "historyCount": 35,
    "status": "無",
    "note": "-",
    "daysPassed": "234天",
    "lastDate": "2025/10/20",
    "isFirstOfCity": false,
    "cityRowspan": 26
  },
  {
    "city": "彰化縣",
    "district": "和美鎮",
    "historyCount": 29,
    "status": "無",
    "note": "-",
    "daysPassed": "209天",
    "lastDate": "2025/11/14",
    "isFirstOfCity": false,
    "cityRowspan": 26
  },
  {
    "city": "彰化縣",
    "district": "鹿港鎮",
    "historyCount": 32,
    "status": "無",
    "note": "-",
    "daysPassed": "239天",
    "lastDate": "2025/10/15",
    "isFirstOfCity": false,
    "cityRowspan": 26
  },
  {
    "city": "彰化縣",
    "district": "福興鄉",
    "historyCount": 29,
    "status": "無",
    "note": "-",
    "daysPassed": "169天",
    "lastDate": "2025/12/24",
    "isFirstOfCity": false,
    "cityRowspan": 26
  },
  {
    "city": "彰化縣",
    "district": "芳苑鄉",
    "historyCount": 32,
    "status": "無",
    "note": "-",
    "daysPassed": "128天",
    "lastDate": "2026/02/03",
    "isFirstOfCity": false,
    "cityRowspan": 26
  },
  {
    "city": "彰化縣",
    "district": "大城鄉",
    "historyCount": 31,
    "status": "無",
    "note": "-",
    "daysPassed": "252天",
    "lastDate": "2025/10/02",
    "isFirstOfCity": false,
    "cityRowspan": 26
  },
  {
    "city": "彰化縣",
    "district": "彰化市",
    "historyCount": 30,
    "status": "無",
    "note": "-",
    "daysPassed": "123天",
    "lastDate": "2026/02/08",
    "isFirstOfCity": false,
    "cityRowspan": 26
  },
  {
    "city": "彰化縣",
    "district": "秀水鄉",
    "historyCount": 31,
    "status": "無",
    "note": "-",
    "daysPassed": "172天",
    "lastDate": "2025/12/21",
    "isFirstOfCity": false,
    "cityRowspan": 26
  },
  {
    "city": "彰化縣",
    "district": "花壇鄉",
    "historyCount": 32,
    "status": "無",
    "note": "-",
    "daysPassed": "186天",
    "lastDate": "2025/12/07",
    "isFirstOfCity": false,
    "cityRowspan": 26
  },
  {
    "city": "彰化縣",
    "district": "芬園鄉",
    "historyCount": 31,
    "status": "無",
    "note": "-",
    "daysPassed": "191天",
    "lastDate": "2025/12/02",
    "isFirstOfCity": false,
    "cityRowspan": 26
  },
  {
    "city": "彰化縣",
    "district": "大村鄉",
    "historyCount": 30,
    "status": "無",
    "note": "-",
    "daysPassed": "256天",
    "lastDate": "2025/09/28",
    "isFirstOfCity": false,
    "cityRowspan": 26
  },
  {
    "city": "彰化縣",
    "district": "員林市",
    "historyCount": 34,
    "status": "無",
    "note": "-",
    "daysPassed": "152天",
    "lastDate": "2026/01/10",
    "isFirstOfCity": false,
    "cityRowspan": 26
  },
  {
    "city": "彰化縣",
    "district": "溪湖鎮",
    "historyCount": 28,
    "status": "無",
    "note": "-",
    "daysPassed": "181天",
    "lastDate": "2025/12/12",
    "isFirstOfCity": false,
    "cityRowspan": 26
  },
  {
    "city": "彰化縣",
    "district": "埔鹽鄉",
    "historyCount": 35,
    "status": "無",
    "note": "-",
    "daysPassed": "134天",
    "lastDate": "2026/01/28",
    "isFirstOfCity": false,
    "cityRowspan": 26
  },
  {
    "city": "彰化縣",
    "district": "埔心鄉",
    "historyCount": 30,
    "status": "無",
    "note": "-",
    "daysPassed": "210天",
    "lastDate": "2025/11/13",
    "isFirstOfCity": false,
    "cityRowspan": 26
  },
  {
    "city": "彰化縣",
    "district": "永靖鄉",
    "historyCount": 35,
    "status": "無",
    "note": "-",
    "daysPassed": "165天",
    "lastDate": "2025/12/28",
    "isFirstOfCity": false,
    "cityRowspan": 26
  },
  {
    "city": "彰化縣",
    "district": "社頭鄉",
    "historyCount": 36,
    "status": "無",
    "note": "-",
    "daysPassed": "273天",
    "lastDate": "2025/09/11",
    "isFirstOfCity": false,
    "cityRowspan": 26
  },
  {
    "city": "彰化縣",
    "district": "田中鎮",
    "historyCount": 33,
    "status": "無",
    "note": "-",
    "daysPassed": "219天",
    "lastDate": "2025/11/04",
    "isFirstOfCity": false,
    "cityRowspan": 26
  },
  {
    "city": "彰化縣",
    "district": "二水鄉",
    "historyCount": 32,
    "status": "無",
    "note": "-",
    "daysPassed": "151天",
    "lastDate": "2026/01/11",
    "isFirstOfCity": false,
    "cityRowspan": 26
  },
  {
    "city": "彰化縣",
    "district": "溪州鄉",
    "historyCount": 35,
    "status": "無",
    "note": "-",
    "daysPassed": "272天",
    "lastDate": "2025/09/12",
    "isFirstOfCity": false,
    "cityRowspan": 26
  },
  {
    "city": "彰化縣",
    "district": "竹塘鄉",
    "historyCount": 36,
    "status": "無",
    "note": "-",
    "daysPassed": "277天",
    "lastDate": "2025/09/07",
    "isFirstOfCity": false,
    "cityRowspan": 26
  },
  {
    "city": "彰化縣",
    "district": "埤頭鄉",
    "historyCount": 32,
    "status": "無",
    "note": "-",
    "daysPassed": "274天",
    "lastDate": "2025/09/10",
    "isFirstOfCity": false,
    "cityRowspan": 26
  },
  {
    "city": "彰化縣",
    "district": "北斗鎮",
    "historyCount": 35,
    "status": "無",
    "note": "-",
    "daysPassed": "276天",
    "lastDate": "2025/09/08",
    "isFirstOfCity": false,
    "cityRowspan": 26
  },
  {
    "city": "彰化縣",
    "district": "田尾鄉",
    "historyCount": 31,
    "status": "無",
    "note": "-",
    "daysPassed": "183天",
    "lastDate": "2025/12/10",
    "isFirstOfCity": false,
    "cityRowspan": 26
  },
  {
    "city": "彰化縣",
    "district": "二林鎮",
    "historyCount": 36,
    "status": "無",
    "note": "-",
    "daysPassed": "255天",
    "lastDate": "2025/09/29",
    "isFirstOfCity": false,
    "cityRowspan": 26
  },
  {
    "city": "南投縣",
    "district": "草屯鎮",
    "historyCount": 35,
    "status": "無",
    "note": "-",
    "daysPassed": "235天",
    "lastDate": "2025/10/19",
    "isFirstOfCity": true,
    "cityRowspan": 13
  },
  {
    "city": "南投縣",
    "district": "國姓鄉",
    "historyCount": 30,
    "status": "無",
    "note": "-",
    "daysPassed": "160天",
    "lastDate": "2026/01/02",
    "isFirstOfCity": false,
    "cityRowspan": 13
  },
  {
    "city": "南投縣",
    "district": "埔里鎮",
    "historyCount": 31,
    "status": "無",
    "note": "-",
    "daysPassed": "260天",
    "lastDate": "2025/09/24",
    "isFirstOfCity": false,
    "cityRowspan": 13
  },
  {
    "city": "南投縣",
    "district": "仁愛鄉",
    "historyCount": 33,
    "status": "無",
    "note": "-",
    "daysPassed": "214天",
    "lastDate": "2025/11/09",
    "isFirstOfCity": false,
    "cityRowspan": 13
  },
  {
    "city": "南投縣",
    "district": "南投市",
    "historyCount": 31,
    "status": "無",
    "note": "-",
    "daysPassed": "276天",
    "lastDate": "2025/09/08",
    "isFirstOfCity": false,
    "cityRowspan": 13
  },
  {
    "city": "南投縣",
    "district": "中寮鄉",
    "historyCount": 35,
    "status": "無",
    "note": "-",
    "daysPassed": "147天",
    "lastDate": "2026/01/15",
    "isFirstOfCity": false,
    "cityRowspan": 13
  },
  {
    "city": "南投縣",
    "district": "魚池鄉",
    "historyCount": 28,
    "status": "無",
    "note": "-",
    "daysPassed": "200天",
    "lastDate": "2025/11/23",
    "isFirstOfCity": false,
    "cityRowspan": 13
  },
  {
    "city": "南投縣",
    "district": "名間鄉",
    "historyCount": 35,
    "status": "無",
    "note": "-",
    "daysPassed": "279天",
    "lastDate": "2025/09/05",
    "isFirstOfCity": false,
    "cityRowspan": 13
  },
  {
    "city": "南投縣",
    "district": "集集鎮",
    "historyCount": 28,
    "status": "無",
    "note": "-",
    "daysPassed": "133天",
    "lastDate": "2026/01/29",
    "isFirstOfCity": false,
    "cityRowspan": 13
  },
  {
    "city": "南投縣",
    "district": "水里鄉",
    "historyCount": 32,
    "status": "無",
    "note": "-",
    "daysPassed": "133天",
    "lastDate": "2026/01/29",
    "isFirstOfCity": false,
    "cityRowspan": 13
  },
  {
    "city": "南投縣",
    "district": "信義鄉",
    "historyCount": 34,
    "status": "無",
    "note": "-",
    "daysPassed": "219天",
    "lastDate": "2025/11/04",
    "isFirstOfCity": false,
    "cityRowspan": 13
  },
  {
    "city": "南投縣",
    "district": "竹山鎮",
    "historyCount": 36,
    "status": "無",
    "note": "-",
    "daysPassed": "137天",
    "lastDate": "2026/01/25",
    "isFirstOfCity": false,
    "cityRowspan": 13
  },
  {
    "city": "南投縣",
    "district": "鹿谷鄉",
    "historyCount": 35,
    "status": "無",
    "note": "-",
    "daysPassed": "248天",
    "lastDate": "2025/10/06",
    "isFirstOfCity": false,
    "cityRowspan": 13
  },
  {
    "city": "雲林縣",
    "district": "麥寮鄉",
    "historyCount": 29,
    "status": "無",
    "note": "-",
    "daysPassed": "185天",
    "lastDate": "2025/12/08",
    "isFirstOfCity": true,
    "cityRowspan": 20
  },
  {
    "city": "雲林縣",
    "district": "崙背鄉",
    "historyCount": 36,
    "status": "無",
    "note": "-",
    "daysPassed": "261天",
    "lastDate": "2025/09/23",
    "isFirstOfCity": false,
    "cityRowspan": 20
  },
  {
    "city": "雲林縣",
    "district": "二崙鄉",
    "historyCount": 35,
    "status": "無",
    "note": "-",
    "daysPassed": "233天",
    "lastDate": "2025/10/21",
    "isFirstOfCity": false,
    "cityRowspan": 20
  },
  {
    "city": "雲林縣",
    "district": "西螺鎮",
    "historyCount": 32,
    "status": "無",
    "note": "-",
    "daysPassed": "265天",
    "lastDate": "2025/09/19",
    "isFirstOfCity": false,
    "cityRowspan": 20
  },
  {
    "city": "雲林縣",
    "district": "莿桐鄉",
    "historyCount": 34,
    "status": "無",
    "note": "-",
    "daysPassed": "253天",
    "lastDate": "2025/10/01",
    "isFirstOfCity": false,
    "cityRowspan": 20
  },
  {
    "city": "雲林縣",
    "district": "林內鄉",
    "historyCount": 28,
    "status": "無",
    "note": "-",
    "daysPassed": "280天",
    "lastDate": "2025/09/04",
    "isFirstOfCity": false,
    "cityRowspan": 20
  },
  {
    "city": "雲林縣",
    "district": "臺西鄉",
    "historyCount": 28,
    "status": "無",
    "note": "-",
    "daysPassed": "206天",
    "lastDate": "2025/11/17",
    "isFirstOfCity": false,
    "cityRowspan": 20
  },
  {
    "city": "雲林縣",
    "district": "東勢鄉",
    "historyCount": 36,
    "status": "無",
    "note": "-",
    "daysPassed": "273天",
    "lastDate": "2025/09/11",
    "isFirstOfCity": false,
    "cityRowspan": 20
  },
  {
    "city": "雲林縣",
    "district": "褒忠鄉",
    "historyCount": 35,
    "status": "無",
    "note": "-",
    "daysPassed": "188天",
    "lastDate": "2025/12/05",
    "isFirstOfCity": false,
    "cityRowspan": 20
  },
  {
    "city": "雲林縣",
    "district": "土庫鎮",
    "historyCount": 28,
    "status": "無",
    "note": "-",
    "daysPassed": "259天",
    "lastDate": "2025/09/25",
    "isFirstOfCity": false,
    "cityRowspan": 20
  },
  {
    "city": "雲林縣",
    "district": "虎尾鎮",
    "historyCount": 31,
    "status": "無",
    "note": "-",
    "daysPassed": "261天",
    "lastDate": "2025/09/23",
    "isFirstOfCity": false,
    "cityRowspan": 20
  },
  {
    "city": "雲林縣",
    "district": "斗六市",
    "historyCount": 34,
    "status": "無",
    "note": "-",
    "daysPassed": "254天",
    "lastDate": "2025/09/30",
    "isFirstOfCity": false,
    "cityRowspan": 20
  },
  {
    "city": "雲林縣",
    "district": "斗南鎮",
    "historyCount": 28,
    "status": "無",
    "note": "-",
    "daysPassed": "259天",
    "lastDate": "2025/09/25",
    "isFirstOfCity": false,
    "cityRowspan": 20
  },
  {
    "city": "雲林縣",
    "district": "古坑鄉",
    "historyCount": 28,
    "status": "無",
    "note": "-",
    "daysPassed": "231天",
    "lastDate": "2025/10/23",
    "isFirstOfCity": false,
    "cityRowspan": 20
  },
  {
    "city": "雲林縣",
    "district": "大埤鄉",
    "historyCount": 35,
    "status": "無",
    "note": "-",
    "daysPassed": "268天",
    "lastDate": "2025/09/16",
    "isFirstOfCity": false,
    "cityRowspan": 20
  },
  {
    "city": "雲林縣",
    "district": "元長鄉",
    "historyCount": 31,
    "status": "無",
    "note": "-",
    "daysPassed": "186天",
    "lastDate": "2025/12/07",
    "isFirstOfCity": false,
    "cityRowspan": 20
  },
  {
    "city": "雲林縣",
    "district": "四湖鄉",
    "historyCount": 33,
    "status": "無",
    "note": "-",
    "daysPassed": "251天",
    "lastDate": "2025/10/03",
    "isFirstOfCity": false,
    "cityRowspan": 20
  },
  {
    "city": "雲林縣",
    "district": "口湖鄉",
    "historyCount": 32,
    "status": "無",
    "note": "-",
    "daysPassed": "241天",
    "lastDate": "2025/10/13",
    "isFirstOfCity": false,
    "cityRowspan": 20
  },
  {
    "city": "雲林縣",
    "district": "水林鄉",
    "historyCount": 28,
    "status": "無",
    "note": "-",
    "daysPassed": "252天",
    "lastDate": "2025/10/02",
    "isFirstOfCity": false,
    "cityRowspan": 20
  },
  {
    "city": "雲林縣",
    "district": "北港鎮",
    "historyCount": 35,
    "status": "無",
    "note": "-",
    "daysPassed": "192天",
    "lastDate": "2025/12/01",
    "isFirstOfCity": false,
    "cityRowspan": 20
  },
  {
    "city": "嘉義市",
    "district": "西區",
    "historyCount": 31,
    "status": "無",
    "note": "-",
    "daysPassed": "232天",
    "lastDate": "2025/10/22",
    "isFirstOfCity": true,
    "cityRowspan": 2
  },
  {
    "city": "嘉義市",
    "district": "東區",
    "historyCount": 30,
    "status": "無",
    "note": "-",
    "daysPassed": "192天",
    "lastDate": "2025/12/01",
    "isFirstOfCity": false,
    "cityRowspan": 2
  },
  {
    "city": "嘉義縣",
    "district": "溪口鄉",
    "historyCount": 31,
    "status": "無",
    "note": "-",
    "daysPassed": "226天",
    "lastDate": "2025/10/28",
    "isFirstOfCity": true,
    "cityRowspan": 18
  },
  {
    "city": "嘉義縣",
    "district": "大林鎮",
    "historyCount": 29,
    "status": "無",
    "note": "-",
    "daysPassed": "147天",
    "lastDate": "2026/01/15",
    "isFirstOfCity": false,
    "cityRowspan": 18
  },
  {
    "city": "嘉義縣",
    "district": "民雄鄉",
    "historyCount": 28,
    "status": "無",
    "note": "-",
    "daysPassed": "192天",
    "lastDate": "2025/12/01",
    "isFirstOfCity": false,
    "cityRowspan": 18
  },
  {
    "city": "嘉義縣",
    "district": "梅山鄉",
    "historyCount": 30,
    "status": "無",
    "note": "-",
    "daysPassed": "127天",
    "lastDate": "2026/02/04",
    "isFirstOfCity": false,
    "cityRowspan": 18
  },
  {
    "city": "嘉義縣",
    "district": "竹崎鄉",
    "historyCount": 35,
    "status": "無",
    "note": "-",
    "daysPassed": "197天",
    "lastDate": "2025/11/26",
    "isFirstOfCity": false,
    "cityRowspan": 18
  },
  {
    "city": "嘉義縣",
    "district": "新港鄉",
    "historyCount": 36,
    "status": "無",
    "note": "-",
    "daysPassed": "205天",
    "lastDate": "2025/11/18",
    "isFirstOfCity": false,
    "cityRowspan": 18
  },
  {
    "city": "嘉義縣",
    "district": "六腳鄉",
    "historyCount": 32,
    "status": "無",
    "note": "-",
    "daysPassed": "196天",
    "lastDate": "2025/11/27",
    "isFirstOfCity": false,
    "cityRowspan": 18
  },
  {
    "city": "嘉義縣",
    "district": "東石鄉",
    "historyCount": 36,
    "status": "無",
    "note": "-",
    "daysPassed": "250天",
    "lastDate": "2025/10/04",
    "isFirstOfCity": false,
    "cityRowspan": 18
  },
  {
    "city": "嘉義縣",
    "district": "朴子市",
    "historyCount": 34,
    "status": "無",
    "note": "-",
    "daysPassed": "237天",
    "lastDate": "2025/10/17",
    "isFirstOfCity": false,
    "cityRowspan": 18
  },
  {
    "city": "嘉義縣",
    "district": "太保市",
    "historyCount": 34,
    "status": "無",
    "note": "-",
    "daysPassed": "131天",
    "lastDate": "2026/01/31",
    "isFirstOfCity": false,
    "cityRowspan": 18
  },
  {
    "city": "嘉義縣",
    "district": "番路鄉",
    "historyCount": 34,
    "status": "無",
    "note": "-",
    "daysPassed": "218天",
    "lastDate": "2025/11/05",
    "isFirstOfCity": false,
    "cityRowspan": 18
  },
  {
    "city": "嘉義縣",
    "district": "阿里山鄉",
    "historyCount": 34,
    "status": "無",
    "note": "-",
    "daysPassed": "269天",
    "lastDate": "2025/09/15",
    "isFirstOfCity": false,
    "cityRowspan": 18
  },
  {
    "city": "嘉義縣",
    "district": "布袋鎮",
    "historyCount": 28,
    "status": "無",
    "note": "-",
    "daysPassed": "278天",
    "lastDate": "2025/09/06",
    "isFirstOfCity": false,
    "cityRowspan": 18
  },
  {
    "city": "嘉義縣",
    "district": "義竹鄉",
    "historyCount": 32,
    "status": "無",
    "note": "-",
    "daysPassed": "237天",
    "lastDate": "2025/10/17",
    "isFirstOfCity": false,
    "cityRowspan": 18
  },
  {
    "city": "嘉義縣",
    "district": "鹿草鄉",
    "historyCount": 35,
    "status": "無",
    "note": "-",
    "daysPassed": "185天",
    "lastDate": "2025/12/08",
    "isFirstOfCity": false,
    "cityRowspan": 18
  },
  {
    "city": "嘉義縣",
    "district": "水上鄉",
    "historyCount": 33,
    "status": "無",
    "note": "-",
    "daysPassed": "280天",
    "lastDate": "2025/09/04",
    "isFirstOfCity": false,
    "cityRowspan": 18
  },
  {
    "city": "嘉義縣",
    "district": "中埔鄉",
    "historyCount": 36,
    "status": "無",
    "note": "-",
    "daysPassed": "159天",
    "lastDate": "2026/01/03",
    "isFirstOfCity": false,
    "cityRowspan": 18
  },
  {
    "city": "嘉義縣",
    "district": "大埔鄉",
    "historyCount": 31,
    "status": "無",
    "note": "-",
    "daysPassed": "232天",
    "lastDate": "2025/10/22",
    "isFirstOfCity": false,
    "cityRowspan": 18
  },
  {
    "city": "台南市",
    "district": "白河區",
    "historyCount": 34,
    "status": "無",
    "note": "-",
    "daysPassed": "278天",
    "lastDate": "2025/09/06",
    "isFirstOfCity": true,
    "cityRowspan": 37
  },
  {
    "city": "台南市",
    "district": "後壁區",
    "historyCount": 35,
    "status": "無",
    "note": "-",
    "daysPassed": "173天",
    "lastDate": "2025/12/20",
    "isFirstOfCity": false,
    "cityRowspan": 37
  },
  {
    "city": "台南市",
    "district": "鹽水區",
    "historyCount": 28,
    "status": "無",
    "note": "-",
    "daysPassed": "169天",
    "lastDate": "2025/12/24",
    "isFirstOfCity": false,
    "cityRowspan": 37
  },
  {
    "city": "台南市",
    "district": "新營區",
    "historyCount": 32,
    "status": "無",
    "note": "-",
    "daysPassed": "235天",
    "lastDate": "2025/10/19",
    "isFirstOfCity": false,
    "cityRowspan": 37
  },
  {
    "city": "台南市",
    "district": "柳營區",
    "historyCount": 32,
    "status": "無",
    "note": "-",
    "daysPassed": "234天",
    "lastDate": "2025/10/20",
    "isFirstOfCity": false,
    "cityRowspan": 37
  },
  {
    "city": "台南市",
    "district": "東山區",
    "historyCount": 36,
    "status": "無",
    "note": "-",
    "daysPassed": "167天",
    "lastDate": "2025/12/26",
    "isFirstOfCity": false,
    "cityRowspan": 37
  },
  {
    "city": "台南市",
    "district": "北門區",
    "historyCount": 36,
    "status": "無",
    "note": "-",
    "daysPassed": "244天",
    "lastDate": "2025/10/10",
    "isFirstOfCity": false,
    "cityRowspan": 37
  },
  {
    "city": "台南市",
    "district": "學甲區",
    "historyCount": 31,
    "status": "無",
    "note": "-",
    "daysPassed": "162天",
    "lastDate": "2025/12/31",
    "isFirstOfCity": false,
    "cityRowspan": 37
  },
  {
    "city": "台南市",
    "district": "下營區",
    "historyCount": 30,
    "status": "無",
    "note": "-",
    "daysPassed": "235天",
    "lastDate": "2025/10/19",
    "isFirstOfCity": false,
    "cityRowspan": 37
  },
  {
    "city": "台南市",
    "district": "六甲區",
    "historyCount": 29,
    "status": "無",
    "note": "-",
    "daysPassed": "184天",
    "lastDate": "2025/12/09",
    "isFirstOfCity": false,
    "cityRowspan": 37
  },
  {
    "city": "台南市",
    "district": "官田區",
    "historyCount": 34,
    "status": "無",
    "note": "-",
    "daysPassed": "274天",
    "lastDate": "2025/09/10",
    "isFirstOfCity": false,
    "cityRowspan": 37
  },
  {
    "city": "台南市",
    "district": "大內區",
    "historyCount": 31,
    "status": "無",
    "note": "-",
    "daysPassed": "123天",
    "lastDate": "2026/02/08",
    "isFirstOfCity": false,
    "cityRowspan": 37
  },
  {
    "city": "台南市",
    "district": "將軍區",
    "historyCount": 32,
    "status": "無",
    "note": "-",
    "daysPassed": "213天",
    "lastDate": "2025/11/10",
    "isFirstOfCity": false,
    "cityRowspan": 37
  },
  {
    "city": "台南市",
    "district": "佳里區",
    "historyCount": 30,
    "status": "無",
    "note": "-",
    "daysPassed": "196天",
    "lastDate": "2025/11/27",
    "isFirstOfCity": false,
    "cityRowspan": 37
  },
  {
    "city": "台南市",
    "district": "麻豆區",
    "historyCount": 29,
    "status": "無",
    "note": "-",
    "daysPassed": "167天",
    "lastDate": "2025/12/26",
    "isFirstOfCity": false,
    "cityRowspan": 37
  },
  {
    "city": "台南市",
    "district": "西港區",
    "historyCount": 36,
    "status": "無",
    "note": "-",
    "daysPassed": "278天",
    "lastDate": "2025/09/06",
    "isFirstOfCity": false,
    "cityRowspan": 37
  },
  {
    "city": "台南市",
    "district": "七股區",
    "historyCount": 31,
    "status": "無",
    "note": "-",
    "daysPassed": "167天",
    "lastDate": "2025/12/26",
    "isFirstOfCity": false,
    "cityRowspan": 37
  },
  {
    "city": "台南市",
    "district": "安定區",
    "historyCount": 33,
    "status": "無",
    "note": "-",
    "daysPassed": "258天",
    "lastDate": "2025/09/26",
    "isFirstOfCity": false,
    "cityRowspan": 37
  },
  {
    "city": "台南市",
    "district": "善化區",
    "historyCount": 32,
    "status": "無",
    "note": "-",
    "daysPassed": "250天",
    "lastDate": "2025/10/04",
    "isFirstOfCity": false,
    "cityRowspan": 37
  },
  {
    "city": "台南市",
    "district": "山上區",
    "historyCount": 29,
    "status": "無",
    "note": "-",
    "daysPassed": "204天",
    "lastDate": "2025/11/19",
    "isFirstOfCity": false,
    "cityRowspan": 37
  },
  {
    "city": "台南市",
    "district": "玉井區",
    "historyCount": 32,
    "status": "無",
    "note": "-",
    "daysPassed": "173天",
    "lastDate": "2025/12/20",
    "isFirstOfCity": false,
    "cityRowspan": 37
  },
  {
    "city": "台南市",
    "district": "楠西區",
    "historyCount": 32,
    "status": "無",
    "note": "-",
    "daysPassed": "175天",
    "lastDate": "2025/12/18",
    "isFirstOfCity": false,
    "cityRowspan": 37
  },
  {
    "city": "台南市",
    "district": "南化區",
    "historyCount": 33,
    "status": "無",
    "note": "-",
    "daysPassed": "210天",
    "lastDate": "2025/11/13",
    "isFirstOfCity": false,
    "cityRowspan": 37
  },
  {
    "city": "台南市",
    "district": "左鎮區",
    "historyCount": 29,
    "status": "無",
    "note": "-",
    "daysPassed": "179天",
    "lastDate": "2025/12/14",
    "isFirstOfCity": false,
    "cityRowspan": 37
  },
  {
    "city": "台南市",
    "district": "新化區",
    "historyCount": 32,
    "status": "無",
    "note": "-",
    "daysPassed": "181天",
    "lastDate": "2025/12/12",
    "isFirstOfCity": false,
    "cityRowspan": 37
  },
  {
    "city": "台南市",
    "district": "新市區",
    "historyCount": 33,
    "status": "無",
    "note": "-",
    "daysPassed": "252天",
    "lastDate": "2025/10/02",
    "isFirstOfCity": false,
    "cityRowspan": 37
  },
  {
    "city": "台南市",
    "district": "永康區",
    "historyCount": 29,
    "status": "無",
    "note": "-",
    "daysPassed": "185天",
    "lastDate": "2025/12/08",
    "isFirstOfCity": false,
    "cityRowspan": 37
  },
  {
    "city": "台南市",
    "district": "安南區",
    "historyCount": 31,
    "status": "無",
    "note": "-",
    "daysPassed": "258天",
    "lastDate": "2025/09/26",
    "isFirstOfCity": false,
    "cityRowspan": 37
  },
  {
    "city": "台南市",
    "district": "北區",
    "historyCount": 28,
    "status": "無",
    "note": "-",
    "daysPassed": "220天",
    "lastDate": "2025/11/03",
    "isFirstOfCity": false,
    "cityRowspan": 37
  },
  {
    "city": "台南市",
    "district": "中西區",
    "historyCount": 32,
    "status": "無",
    "note": "-",
    "daysPassed": "220天",
    "lastDate": "2025/11/03",
    "isFirstOfCity": false,
    "cityRowspan": 37
  },
  {
    "city": "台南市",
    "district": "東區",
    "historyCount": 36,
    "status": "無",
    "note": "-",
    "daysPassed": "208天",
    "lastDate": "2025/11/15",
    "isFirstOfCity": false,
    "cityRowspan": 37
  },
  {
    "city": "台南市",
    "district": "安平區",
    "historyCount": 31,
    "status": "無",
    "note": "-",
    "daysPassed": "138天",
    "lastDate": "2026/01/24",
    "isFirstOfCity": false,
    "cityRowspan": 37
  },
  {
    "city": "台南市",
    "district": "南區",
    "historyCount": 28,
    "status": "無",
    "note": "-",
    "daysPassed": "160天",
    "lastDate": "2026/01/02",
    "isFirstOfCity": false,
    "cityRowspan": 37
  },
  {
    "city": "台南市",
    "district": "仁德區",
    "historyCount": 28,
    "status": "無",
    "note": "-",
    "daysPassed": "228天",
    "lastDate": "2025/10/26",
    "isFirstOfCity": false,
    "cityRowspan": 37
  },
  {
    "city": "台南市",
    "district": "歸仁區",
    "historyCount": 34,
    "status": "無",
    "note": "-",
    "daysPassed": "198天",
    "lastDate": "2025/11/25",
    "isFirstOfCity": false,
    "cityRowspan": 37
  },
  {
    "city": "台南市",
    "district": "關廟區",
    "historyCount": 33,
    "status": "無",
    "note": "-",
    "daysPassed": "140天",
    "lastDate": "2026/01/22",
    "isFirstOfCity": false,
    "cityRowspan": 37
  },
  {
    "city": "台南市",
    "district": "龍崎區",
    "historyCount": 36,
    "status": "無",
    "note": "-",
    "daysPassed": "152天",
    "lastDate": "2026/01/10",
    "isFirstOfCity": false,
    "cityRowspan": 37
  },
  {
    "city": "高雄市",
    "district": "茄萣區",
    "historyCount": 33,
    "status": "無",
    "note": "-",
    "daysPassed": "268天",
    "lastDate": "2025/09/16",
    "isFirstOfCity": true,
    "cityRowspan": 38
  },
  {
    "city": "高雄市",
    "district": "湖內區",
    "historyCount": 33,
    "status": "無",
    "note": "-",
    "daysPassed": "254天",
    "lastDate": "2025/09/30",
    "isFirstOfCity": false,
    "cityRowspan": 38
  },
  {
    "city": "高雄市",
    "district": "路竹區",
    "historyCount": 30,
    "status": "無",
    "note": "-",
    "daysPassed": "256天",
    "lastDate": "2025/09/28",
    "isFirstOfCity": false,
    "cityRowspan": 38
  },
  {
    "city": "高雄市",
    "district": "阿蓮區",
    "historyCount": 28,
    "status": "無",
    "note": "-",
    "daysPassed": "246天",
    "lastDate": "2025/10/08",
    "isFirstOfCity": false,
    "cityRowspan": 38
  },
  {
    "city": "高雄市",
    "district": "田寮區",
    "historyCount": 30,
    "status": "無",
    "note": "-",
    "daysPassed": "249天",
    "lastDate": "2025/10/05",
    "isFirstOfCity": false,
    "cityRowspan": 38
  },
  {
    "city": "高雄市",
    "district": "內門區",
    "historyCount": 36,
    "status": "無",
    "note": "-",
    "daysPassed": "136天",
    "lastDate": "2026/01/26",
    "isFirstOfCity": false,
    "cityRowspan": 38
  },
  {
    "city": "高雄市",
    "district": "旗山區",
    "historyCount": 33,
    "status": "無",
    "note": "-",
    "daysPassed": "175天",
    "lastDate": "2025/12/18",
    "isFirstOfCity": false,
    "cityRowspan": 38
  },
  {
    "city": "高雄市",
    "district": "美濃區",
    "historyCount": 33,
    "status": "無",
    "note": "-",
    "daysPassed": "171天",
    "lastDate": "2025/12/22",
    "isFirstOfCity": false,
    "cityRowspan": 38
  },
  {
    "city": "高雄市",
    "district": "六龜區",
    "historyCount": 35,
    "status": "無",
    "note": "-",
    "daysPassed": "237天",
    "lastDate": "2025/10/17",
    "isFirstOfCity": false,
    "cityRowspan": 38
  },
  {
    "city": "高雄市",
    "district": "甲仙區",
    "historyCount": 31,
    "status": "無",
    "note": "-",
    "daysPassed": "210天",
    "lastDate": "2025/11/13",
    "isFirstOfCity": false,
    "cityRowspan": 38
  },
  {
    "city": "高雄市",
    "district": "杉林區",
    "historyCount": 30,
    "status": "無",
    "note": "-",
    "daysPassed": "251天",
    "lastDate": "2025/10/03",
    "isFirstOfCity": false,
    "cityRowspan": 38
  },
  {
    "city": "高雄市",
    "district": "那瑪夏區",
    "historyCount": 29,
    "status": "無",
    "note": "-",
    "daysPassed": "169天",
    "lastDate": "2025/12/24",
    "isFirstOfCity": false,
    "cityRowspan": 38
  },
  {
    "city": "高雄市",
    "district": "桃源區",
    "historyCount": 34,
    "status": "無",
    "note": "-",
    "daysPassed": "189天",
    "lastDate": "2025/12/04",
    "isFirstOfCity": false,
    "cityRowspan": 38
  },
  {
    "city": "高雄市",
    "district": "茂林區",
    "historyCount": 28,
    "status": "無",
    "note": "-",
    "daysPassed": "134天",
    "lastDate": "2026/01/28",
    "isFirstOfCity": false,
    "cityRowspan": 38
  },
  {
    "city": "高雄市",
    "district": "永安區",
    "historyCount": 30,
    "status": "無",
    "note": "-",
    "daysPassed": "135天",
    "lastDate": "2026/01/27",
    "isFirstOfCity": false,
    "cityRowspan": 38
  },
  {
    "city": "高雄市",
    "district": "彌陀區",
    "historyCount": 36,
    "status": "無",
    "note": "-",
    "daysPassed": "212天",
    "lastDate": "2025/11/11",
    "isFirstOfCity": false,
    "cityRowspan": 38
  },
  {
    "city": "高雄市",
    "district": "岡山區",
    "historyCount": 33,
    "status": "無",
    "note": "-",
    "daysPassed": "187天",
    "lastDate": "2025/12/06",
    "isFirstOfCity": false,
    "cityRowspan": 38
  },
  {
    "city": "高雄市",
    "district": "燕巢區",
    "historyCount": 36,
    "status": "無",
    "note": "-",
    "daysPassed": "277天",
    "lastDate": "2025/09/07",
    "isFirstOfCity": false,
    "cityRowspan": 38
  },
  {
    "city": "高雄市",
    "district": "橋頭區",
    "historyCount": 33,
    "status": "無",
    "note": "-",
    "daysPassed": "145天",
    "lastDate": "2026/01/17",
    "isFirstOfCity": false,
    "cityRowspan": 38
  },
  {
    "city": "高雄市",
    "district": "梓官區",
    "historyCount": 29,
    "status": "無",
    "note": "-",
    "daysPassed": "157天",
    "lastDate": "2026/01/05",
    "isFirstOfCity": false,
    "cityRowspan": 38
  },
  {
    "city": "高雄市",
    "district": "楠梓區",
    "historyCount": 30,
    "status": "無",
    "note": "-",
    "daysPassed": "167天",
    "lastDate": "2025/12/26",
    "isFirstOfCity": false,
    "cityRowspan": 38
  },
  {
    "city": "高雄市",
    "district": "左營區",
    "historyCount": 36,
    "status": "無",
    "note": "-",
    "daysPassed": "182天",
    "lastDate": "2025/12/11",
    "isFirstOfCity": false,
    "cityRowspan": 38
  },
  {
    "city": "高雄市",
    "district": "三民區",
    "historyCount": 32,
    "status": "無",
    "note": "-",
    "daysPassed": "178天",
    "lastDate": "2025/12/15",
    "isFirstOfCity": false,
    "cityRowspan": 38
  },
  {
    "city": "高雄市",
    "district": "鼓山區",
    "historyCount": 29,
    "status": "無",
    "note": "-",
    "daysPassed": "268天",
    "lastDate": "2025/09/16",
    "isFirstOfCity": false,
    "cityRowspan": 38
  },
  {
    "city": "高雄市",
    "district": "鹽埕區",
    "historyCount": 29,
    "status": "無",
    "note": "-",
    "daysPassed": "255天",
    "lastDate": "2025/09/29",
    "isFirstOfCity": false,
    "cityRowspan": 38
  },
  {
    "city": "高雄市",
    "district": "前金區",
    "historyCount": 28,
    "status": "無",
    "note": "-",
    "daysPassed": "267天",
    "lastDate": "2025/09/17",
    "isFirstOfCity": false,
    "cityRowspan": 38
  },
  {
    "city": "高雄市",
    "district": "新興區",
    "historyCount": 35,
    "status": "無",
    "note": "-",
    "daysPassed": "177天",
    "lastDate": "2025/12/16",
    "isFirstOfCity": false,
    "cityRowspan": 38
  },
  {
    "city": "高雄市",
    "district": "苓雅區",
    "historyCount": 36,
    "status": "無",
    "note": "-",
    "daysPassed": "135天",
    "lastDate": "2026/01/27",
    "isFirstOfCity": false,
    "cityRowspan": 38
  },
  {
    "city": "高雄市",
    "district": "前鎮區",
    "historyCount": 29,
    "status": "無",
    "note": "-",
    "daysPassed": "223天",
    "lastDate": "2025/10/31",
    "isFirstOfCity": false,
    "cityRowspan": 38
  },
  {
    "city": "高雄市",
    "district": "旗津區",
    "historyCount": 30,
    "status": "無",
    "note": "-",
    "daysPassed": "139天",
    "lastDate": "2026/01/23",
    "isFirstOfCity": false,
    "cityRowspan": 38
  },
  {
    "city": "高雄市",
    "district": "小港區",
    "historyCount": 33,
    "status": "無",
    "note": "-",
    "daysPassed": "176天",
    "lastDate": "2025/12/17",
    "isFirstOfCity": false,
    "cityRowspan": 38
  },
  {
    "city": "高雄市",
    "district": "鳳山區",
    "historyCount": 32,
    "status": "無",
    "note": "-",
    "daysPassed": "182天",
    "lastDate": "2025/12/11",
    "isFirstOfCity": false,
    "cityRowspan": 38
  },
  {
    "city": "高雄市",
    "district": "鳥松區",
    "historyCount": 33,
    "status": "無",
    "note": "-",
    "daysPassed": "245天",
    "lastDate": "2025/10/09",
    "isFirstOfCity": false,
    "cityRowspan": 38
  },
  {
    "city": "高雄市",
    "district": "仁武區",
    "historyCount": 35,
    "status": "無",
    "note": "-",
    "daysPassed": "263天",
    "lastDate": "2025/09/21",
    "isFirstOfCity": false,
    "cityRowspan": 38
  },
  {
    "city": "高雄市",
    "district": "大社區",
    "historyCount": 33,
    "status": "無",
    "note": "-",
    "daysPassed": "221天",
    "lastDate": "2025/11/02",
    "isFirstOfCity": false,
    "cityRowspan": 38
  },
  {
    "city": "高雄市",
    "district": "大樹區",
    "historyCount": 33,
    "status": "無",
    "note": "-",
    "daysPassed": "210天",
    "lastDate": "2025/11/13",
    "isFirstOfCity": false,
    "cityRowspan": 38
  },
  {
    "city": "高雄市",
    "district": "大寮區",
    "historyCount": 34,
    "status": "無",
    "note": "-",
    "daysPassed": "163天",
    "lastDate": "2025/12/30",
    "isFirstOfCity": false,
    "cityRowspan": 38
  },
  {
    "city": "高雄市",
    "district": "林園區",
    "historyCount": 29,
    "status": "無",
    "note": "-",
    "daysPassed": "138天",
    "lastDate": "2026/01/24",
    "isFirstOfCity": false,
    "cityRowspan": 38
  },
  {
    "city": "屏東縣",
    "district": "高樹鄉",
    "historyCount": 29,
    "status": "無",
    "note": "-",
    "daysPassed": "151天",
    "lastDate": "2026/01/11",
    "isFirstOfCity": true,
    "cityRowspan": 33
  },
  {
    "city": "屏東縣",
    "district": "三地門鄉",
    "historyCount": 31,
    "status": "停止上班上課",
    "note": "-",
    "daysPassed": "0天 (今天)",
    "lastDate": "2026/06/11",
    "isFirstOfCity": false,
    "cityRowspan": 33
  },
  {
    "city": "屏東縣",
    "district": "霧臺鄉",
    "historyCount": 31,
    "status": "無",
    "note": "-",
    "daysPassed": "157天",
    "lastDate": "2026/01/05",
    "isFirstOfCity": false,
    "cityRowspan": 33
  },
  {
    "city": "屏東縣",
    "district": "里港鄉",
    "historyCount": 28,
    "status": "無",
    "note": "-",
    "daysPassed": "278天",
    "lastDate": "2025/09/06",
    "isFirstOfCity": false,
    "cityRowspan": 33
  },
  {
    "city": "屏東縣",
    "district": "九如鄉",
    "historyCount": 33,
    "status": "無",
    "note": "-",
    "daysPassed": "270天",
    "lastDate": "2025/09/14",
    "isFirstOfCity": false,
    "cityRowspan": 33
  },
  {
    "city": "屏東縣",
    "district": "鹽埔鄉",
    "historyCount": 29,
    "status": "無",
    "note": "-",
    "daysPassed": "267天",
    "lastDate": "2025/09/17",
    "isFirstOfCity": false,
    "cityRowspan": 33
  },
  {
    "city": "屏東縣",
    "district": "長治鄉",
    "historyCount": 32,
    "status": "無",
    "note": "-",
    "daysPassed": "245天",
    "lastDate": "2025/10/09",
    "isFirstOfCity": false,
    "cityRowspan": 33
  },
  {
    "city": "屏東縣",
    "district": "屏東市",
    "historyCount": 30,
    "status": "無",
    "note": "-",
    "daysPassed": "269天",
    "lastDate": "2025/09/15",
    "isFirstOfCity": false,
    "cityRowspan": 33
  },
  {
    "city": "屏東縣",
    "district": "麟洛鄉",
    "historyCount": 30,
    "status": "無",
    "note": "-",
    "daysPassed": "216天",
    "lastDate": "2025/11/07",
    "isFirstOfCity": false,
    "cityRowspan": 33
  },
  {
    "city": "屏東縣",
    "district": "內埔鄉",
    "historyCount": 31,
    "status": "無",
    "note": "-",
    "daysPassed": "265天",
    "lastDate": "2025/09/19",
    "isFirstOfCity": false,
    "cityRowspan": 33
  },
  {
    "city": "屏東縣",
    "district": "瑪家鄉",
    "historyCount": 35,
    "status": "無",
    "note": "-",
    "daysPassed": "145天",
    "lastDate": "2026/01/17",
    "isFirstOfCity": false,
    "cityRowspan": 33
  },
  {
    "city": "屏東縣",
    "district": "泰武鄉",
    "historyCount": 36,
    "status": "無",
    "note": "-",
    "daysPassed": "185天",
    "lastDate": "2025/12/08",
    "isFirstOfCity": false,
    "cityRowspan": 33
  },
  {
    "city": "屏東縣",
    "district": "萬巒鄉",
    "historyCount": 33,
    "status": "無",
    "note": "-",
    "daysPassed": "132天",
    "lastDate": "2026/01/30",
    "isFirstOfCity": false,
    "cityRowspan": 33
  },
  {
    "city": "屏東縣",
    "district": "竹田鄉",
    "historyCount": 34,
    "status": "無",
    "note": "-",
    "daysPassed": "251天",
    "lastDate": "2025/10/03",
    "isFirstOfCity": false,
    "cityRowspan": 33
  },
  {
    "city": "屏東縣",
    "district": "萬丹鄉",
    "historyCount": 30,
    "status": "無",
    "note": "-",
    "daysPassed": "189天",
    "lastDate": "2025/12/04",
    "isFirstOfCity": false,
    "cityRowspan": 33
  },
  {
    "city": "屏東縣",
    "district": "新園鄉",
    "historyCount": 29,
    "status": "無",
    "note": "-",
    "daysPassed": "178天",
    "lastDate": "2025/12/15",
    "isFirstOfCity": false,
    "cityRowspan": 33
  },
  {
    "city": "屏東縣",
    "district": "崁頂鄉",
    "historyCount": 35,
    "status": "無",
    "note": "-",
    "daysPassed": "201天",
    "lastDate": "2025/11/22",
    "isFirstOfCity": false,
    "cityRowspan": 33
  },
  {
    "city": "屏東縣",
    "district": "潮州鎮",
    "historyCount": 32,
    "status": "無",
    "note": "-",
    "daysPassed": "213天",
    "lastDate": "2025/11/10",
    "isFirstOfCity": false,
    "cityRowspan": 33
  },
  {
    "city": "屏東縣",
    "district": "來義鄉",
    "historyCount": 30,
    "status": "無",
    "note": "-",
    "daysPassed": "262天",
    "lastDate": "2025/09/22",
    "isFirstOfCity": false,
    "cityRowspan": 33
  },
  {
    "city": "屏東縣",
    "district": "新埤鄉",
    "historyCount": 29,
    "status": "無",
    "note": "-",
    "daysPassed": "121天",
    "lastDate": "2026/02/10",
    "isFirstOfCity": false,
    "cityRowspan": 33
  },
  {
    "city": "屏東縣",
    "district": "南州鄉",
    "historyCount": 31,
    "status": "無",
    "note": "-",
    "daysPassed": "191天",
    "lastDate": "2025/12/02",
    "isFirstOfCity": false,
    "cityRowspan": 33
  },
  {
    "city": "屏東縣",
    "district": "東港鎮",
    "historyCount": 32,
    "status": "無",
    "note": "-",
    "daysPassed": "151天",
    "lastDate": "2026/01/11",
    "isFirstOfCity": false,
    "cityRowspan": 33
  },
  {
    "city": "屏東縣",
    "district": "琉球鄉",
    "historyCount": 35,
    "status": "無",
    "note": "-",
    "daysPassed": "177天",
    "lastDate": "2025/12/16",
    "isFirstOfCity": false,
    "cityRowspan": 33
  },
  {
    "city": "屏東縣",
    "district": "佳冬鄉",
    "historyCount": 35,
    "status": "無",
    "note": "-",
    "daysPassed": "165天",
    "lastDate": "2025/12/28",
    "isFirstOfCity": false,
    "cityRowspan": 33
  },
  {
    "city": "屏東縣",
    "district": "林邊鄉",
    "historyCount": 30,
    "status": "無",
    "note": "-",
    "daysPassed": "123天",
    "lastDate": "2026/02/08",
    "isFirstOfCity": false,
    "cityRowspan": 33
  },
  {
    "city": "屏東縣",
    "district": "仿寮鄉",
    "historyCount": 36,
    "status": "無",
    "note": "-",
    "daysPassed": "155天",
    "lastDate": "2026/01/07",
    "isFirstOfCity": false,
    "cityRowspan": 33
  },
  {
    "city": "屏東縣",
    "district": "春日鄉",
    "historyCount": 36,
    "status": "無",
    "note": "-",
    "daysPassed": "233天",
    "lastDate": "2025/10/21",
    "isFirstOfCity": false,
    "cityRowspan": 33
  },
  {
    "city": "屏東縣",
    "district": "枋山鄉",
    "historyCount": 32,
    "status": "無",
    "note": "-",
    "daysPassed": "142天",
    "lastDate": "2026/01/20",
    "isFirstOfCity": false,
    "cityRowspan": 33
  },
  {
    "city": "屏東縣",
    "district": "獅子鄉",
    "historyCount": 32,
    "status": "無",
    "note": "-",
    "daysPassed": "147天",
    "lastDate": "2026/01/15",
    "isFirstOfCity": false,
    "cityRowspan": 33
  },
  {
    "city": "屏東縣",
    "district": "車城鄉",
    "historyCount": 36,
    "status": "無",
    "note": "-",
    "daysPassed": "167天",
    "lastDate": "2025/12/26",
    "isFirstOfCity": false,
    "cityRowspan": 33
  },
  {
    "city": "屏東縣",
    "district": "牡丹鄉",
    "historyCount": 34,
    "status": "無",
    "note": "-",
    "daysPassed": "243天",
    "lastDate": "2025/10/11",
    "isFirstOfCity": false,
    "cityRowspan": 33
  },
  {
    "city": "屏東縣",
    "district": "恆春鎮",
    "historyCount": 30,
    "status": "無",
    "note": "-",
    "daysPassed": "123天",
    "lastDate": "2026/02/08",
    "isFirstOfCity": false,
    "cityRowspan": 33
  },
  {
    "city": "屏東縣",
    "district": "滿州鄉",
    "historyCount": 36,
    "status": "無",
    "note": "-",
    "daysPassed": "262天",
    "lastDate": "2025/09/22",
    "isFirstOfCity": false,
    "cityRowspan": 33
  },
  {
    "city": "宜蘭縣",
    "district": "頭城鎮",
    "historyCount": 28,
    "status": "無",
    "note": "-",
    "daysPassed": "199天",
    "lastDate": "2025/11/24",
    "isFirstOfCity": true,
    "cityRowspan": 12
  },
  {
    "city": "宜蘭縣",
    "district": "礁溪鄉",
    "historyCount": 33,
    "status": "無",
    "note": "-",
    "daysPassed": "277天",
    "lastDate": "2025/09/07",
    "isFirstOfCity": false,
    "cityRowspan": 12
  },
  {
    "city": "宜蘭縣",
    "district": "壯圍鄉",
    "historyCount": 30,
    "status": "無",
    "note": "-",
    "daysPassed": "240天",
    "lastDate": "2025/10/14",
    "isFirstOfCity": false,
    "cityRowspan": 12
  },
  {
    "city": "宜蘭縣",
    "district": "宜蘭市",
    "historyCount": 34,
    "status": "無",
    "note": "-",
    "daysPassed": "190天",
    "lastDate": "2025/12/03",
    "isFirstOfCity": false,
    "cityRowspan": 12
  },
  {
    "city": "宜蘭縣",
    "district": "員山鄉",
    "historyCount": 34,
    "status": "無",
    "note": "-",
    "daysPassed": "120天",
    "lastDate": "2026/02/11",
    "isFirstOfCity": false,
    "cityRowspan": 12
  },
  {
    "city": "宜蘭縣",
    "district": "五結鄉",
    "historyCount": 28,
    "status": "無",
    "note": "-",
    "daysPassed": "128天",
    "lastDate": "2026/02/03",
    "isFirstOfCity": false,
    "cityRowspan": 12
  },
  {
    "city": "宜蘭縣",
    "district": "羅東鎮",
    "historyCount": 36,
    "status": "無",
    "note": "-",
    "daysPassed": "250天",
    "lastDate": "2025/10/04",
    "isFirstOfCity": false,
    "cityRowspan": 12
  },
  {
    "city": "宜蘭縣",
    "district": "三星鄉",
    "historyCount": 34,
    "status": "無",
    "note": "-",
    "daysPassed": "250天",
    "lastDate": "2025/10/04",
    "isFirstOfCity": false,
    "cityRowspan": 12
  },
  {
    "city": "宜蘭縣",
    "district": "大同鄉",
    "historyCount": 32,
    "status": "無",
    "note": "-",
    "daysPassed": "249天",
    "lastDate": "2025/10/05",
    "isFirstOfCity": false,
    "cityRowspan": 12
  },
  {
    "city": "宜蘭縣",
    "district": "冬山鄉",
    "historyCount": 30,
    "status": "無",
    "note": "-",
    "daysPassed": "192天",
    "lastDate": "2025/12/01",
    "isFirstOfCity": false,
    "cityRowspan": 12
  },
  {
    "city": "宜蘭縣",
    "district": "蘇澳鎮",
    "historyCount": 35,
    "status": "無",
    "note": "-",
    "daysPassed": "222天",
    "lastDate": "2025/11/01",
    "isFirstOfCity": false,
    "cityRowspan": 12
  },
  {
    "city": "宜蘭縣",
    "district": "南澳鄉",
    "historyCount": 28,
    "status": "無",
    "note": "-",
    "daysPassed": "243天",
    "lastDate": "2025/10/11",
    "isFirstOfCity": false,
    "cityRowspan": 12
  },
  {
    "city": "花蓮縣",
    "district": "秀林鄉",
    "historyCount": 30,
    "status": "無",
    "note": "-",
    "daysPassed": "200天",
    "lastDate": "2025/11/23",
    "isFirstOfCity": true,
    "cityRowspan": 13
  },
  {
    "city": "花蓮縣",
    "district": "新城鄉",
    "historyCount": 31,
    "status": "無",
    "note": "-",
    "daysPassed": "128天",
    "lastDate": "2026/02/03",
    "isFirstOfCity": false,
    "cityRowspan": 13
  },
  {
    "city": "花蓮縣",
    "district": "花蓮市",
    "historyCount": 34,
    "status": "無",
    "note": "-",
    "daysPassed": "262天",
    "lastDate": "2025/09/22",
    "isFirstOfCity": false,
    "cityRowspan": 13
  },
  {
    "city": "花蓮縣",
    "district": "吉安鄉",
    "historyCount": 35,
    "status": "無",
    "note": "-",
    "daysPassed": "267天",
    "lastDate": "2025/09/17",
    "isFirstOfCity": false,
    "cityRowspan": 13
  },
  {
    "city": "花蓮縣",
    "district": "壽豐鄉",
    "historyCount": 32,
    "status": "無",
    "note": "-",
    "daysPassed": "203天",
    "lastDate": "2025/11/20",
    "isFirstOfCity": false,
    "cityRowspan": 13
  },
  {
    "city": "花蓮縣",
    "district": "鳳林鎮",
    "historyCount": 32,
    "status": "無",
    "note": "-",
    "daysPassed": "268天",
    "lastDate": "2025/09/16",
    "isFirstOfCity": false,
    "cityRowspan": 13
  },
  {
    "city": "花蓮縣",
    "district": "萬榮鄉",
    "historyCount": 33,
    "status": "無",
    "note": "-",
    "daysPassed": "151天",
    "lastDate": "2026/01/11",
    "isFirstOfCity": false,
    "cityRowspan": 13
  },
  {
    "city": "花蓮縣",
    "district": "光復鄉",
    "historyCount": 34,
    "status": "無",
    "note": "-",
    "daysPassed": "226天",
    "lastDate": "2025/10/28",
    "isFirstOfCity": false,
    "cityRowspan": 13
  },
  {
    "city": "花蓮縣",
    "district": "豐濱鄉",
    "historyCount": 33,
    "status": "無",
    "note": "-",
    "daysPassed": "272天",
    "lastDate": "2025/09/12",
    "isFirstOfCity": false,
    "cityRowspan": 13
  },
  {
    "city": "花蓮縣",
    "district": "瑞穗鄉",
    "historyCount": 34,
    "status": "無",
    "note": "-",
    "daysPassed": "206天",
    "lastDate": "2025/11/17",
    "isFirstOfCity": false,
    "cityRowspan": 13
  },
  {
    "city": "花蓮縣",
    "district": "玉里鎮",
    "historyCount": 36,
    "status": "無",
    "note": "-",
    "daysPassed": "140天",
    "lastDate": "2026/01/22",
    "isFirstOfCity": false,
    "cityRowspan": 13
  },
  {
    "city": "花蓮縣",
    "district": "卓溪鄉",
    "historyCount": 30,
    "status": "無",
    "note": "-",
    "daysPassed": "125天",
    "lastDate": "2026/02/06",
    "isFirstOfCity": false,
    "cityRowspan": 13
  },
  {
    "city": "花蓮縣",
    "district": "富里鄉",
    "historyCount": 34,
    "status": "無",
    "note": "-",
    "daysPassed": "277天",
    "lastDate": "2025/09/07",
    "isFirstOfCity": false,
    "cityRowspan": 13
  },
  {
    "city": "台東縣",
    "district": "長濱鄉",
    "historyCount": 35,
    "status": "無",
    "note": "-",
    "daysPassed": "176天",
    "lastDate": "2025/12/17",
    "isFirstOfCity": true,
    "cityRowspan": 16
  },
  {
    "city": "台東縣",
    "district": "海端鄉",
    "historyCount": 32,
    "status": "無",
    "note": "-",
    "daysPassed": "154天",
    "lastDate": "2026/01/08",
    "isFirstOfCity": false,
    "cityRowspan": 16
  },
  {
    "city": "台東縣",
    "district": "池上鄉",
    "historyCount": 34,
    "status": "無",
    "note": "-",
    "daysPassed": "223天",
    "lastDate": "2025/10/31",
    "isFirstOfCity": false,
    "cityRowspan": 16
  },
  {
    "city": "台東縣",
    "district": "成功鎮",
    "historyCount": 30,
    "status": "無",
    "note": "-",
    "daysPassed": "154天",
    "lastDate": "2026/01/08",
    "isFirstOfCity": false,
    "cityRowspan": 16
  },
  {
    "city": "台東縣",
    "district": "關山鎮",
    "historyCount": 31,
    "status": "無",
    "note": "-",
    "daysPassed": "214天",
    "lastDate": "2025/11/09",
    "isFirstOfCity": false,
    "cityRowspan": 16
  },
  {
    "city": "台東縣",
    "district": "鹿野鄉",
    "historyCount": 33,
    "status": "無",
    "note": "-",
    "daysPassed": "245天",
    "lastDate": "2025/10/09",
    "isFirstOfCity": false,
    "cityRowspan": 16
  },
  {
    "city": "台東縣",
    "district": "東河鄉",
    "historyCount": 28,
    "status": "無",
    "note": "-",
    "daysPassed": "136天",
    "lastDate": "2026/01/26",
    "isFirstOfCity": false,
    "cityRowspan": 16
  },
  {
    "city": "台東縣",
    "district": "延平鄉",
    "historyCount": 28,
    "status": "無",
    "note": "-",
    "daysPassed": "268天",
    "lastDate": "2025/09/16",
    "isFirstOfCity": false,
    "cityRowspan": 16
  },
  {
    "city": "台東縣",
    "district": "卑南鄉",
    "historyCount": 31,
    "status": "無",
    "note": "-",
    "daysPassed": "177天",
    "lastDate": "2025/12/16",
    "isFirstOfCity": false,
    "cityRowspan": 16
  },
  {
    "city": "台東縣",
    "district": "臺東市",
    "historyCount": 28,
    "status": "無",
    "note": "-",
    "daysPassed": "180天",
    "lastDate": "2025/12/13",
    "isFirstOfCity": false,
    "cityRowspan": 16
  },
  {
    "city": "台東縣",
    "district": "太麻里鄉",
    "historyCount": 29,
    "status": "無",
    "note": "-",
    "daysPassed": "156天",
    "lastDate": "2026/01/06",
    "isFirstOfCity": false,
    "cityRowspan": 16
  },
  {
    "city": "台東縣",
    "district": "金峰鄉",
    "historyCount": 34,
    "status": "無",
    "note": "-",
    "daysPassed": "197天",
    "lastDate": "2025/11/26",
    "isFirstOfCity": false,
    "cityRowspan": 16
  },
  {
    "city": "台東縣",
    "district": "大武鄉",
    "historyCount": 33,
    "status": "無",
    "note": "-",
    "daysPassed": "166天",
    "lastDate": "2025/12/27",
    "isFirstOfCity": false,
    "cityRowspan": 16
  },
  {
    "city": "台東縣",
    "district": "達仁鄉",
    "historyCount": 36,
    "status": "無",
    "note": "-",
    "daysPassed": "186天",
    "lastDate": "2025/12/07",
    "isFirstOfCity": false,
    "cityRowspan": 16
  },
  {
    "city": "台東縣",
    "district": "綠島鄉",
    "historyCount": 31,
    "status": "無",
    "note": "-",
    "daysPassed": "171天",
    "lastDate": "2025/12/22",
    "isFirstOfCity": false,
    "cityRowspan": 16
  },
  {
    "city": "台東縣",
    "district": "蘭嶼鄉",
    "historyCount": 30,
    "status": "無",
    "note": "-",
    "daysPassed": "199天",
    "lastDate": "2025/11/24",
    "isFirstOfCity": false,
    "cityRowspan": 16
  }
];
